### ISSUE TITLE
Implement Recipes collection

### ISSUE THREAD

**Issue by kleve84** [manoarecipes/manoarecipes#11]
Create recipe collection for new and existing recipes. Consisting of the following documents:
Name:String, Description:String, Ingredients:Array, Instructions:Array, Picture:SimpleSchema, Tags:Array

**Comment by kleve84** [comment]
Collection implemented but the following error pops when running the application:

W20171128-10:12:11.523(-10)? (STDERR) Error: Match error: Expected string, got undefined
W20171128-10:12:11.523(-10)? (STDERR)     at exports.check (packages/check.js:55:15)
W20171128-10:12:11.524(-10)? (STDERR)     at IngredientsCollection.define (imports/api/ingredients/IngredientsCollection.js:39:5)
W20171128-10:12:11.525(-10)? (STDERR)     at imports/startup/server/initialize-database.js:29:48
W20171128-10:12:11.525(-10)? (STDERR)     at Array.forEach (native)
W20171128-10:12:11.526(-10)? (STDERR)     at Function._.each._.forEach (packages/underscore.js:139:11)
W20171128-10:12:11.526(-10)? (STDERR)     at restoreCollection (imports/startup/server/initialize-database.js:29:5)
W20171128-10:12:11.527(-10)? (STDERR)     at imports/startup/server/initialize-database.js:43:7
W20171128-10:12:11.527(-10)? (STDERR)     at Array.forEach (native)
W20171128-10:12:11.528(-10)? (STDERR)     at Function._.each._.forEach (packages/underscore.js:139:11)
W20171128-10:12:11.528(-10)? (STDERR)     at imports/startup/server/initialize-database.js:42:7
=> Exited with code: 1

Something to do with the Ingredients collection as I've tested each collection startup separately.

**Comment by kleve84** [comment]
Bug was document names in InterestCollection were still "description" when they should've been "cost". Also changed the order in which the collections were initialized.
